### ISSUE TITLE
Is it possible that header <metal_simdgroup_future> included using JIT compilation？

### ISSUE THREAD

**Issue by FdyCN** [philipturner/metal-flash-attention#10]
the AOT metal kernel including a header named `<metal_simdgroup_future>`，
https://github.com/philipturner/metal-flash-attention/blob/32592c98eff18001d4eec2c7a204e288fa92fa44/Sources/metal_simdgroup_event#L14

seemed it contained in Xcode SDK，so i wonder that if it's possible to inculde this header in JIT metal kernel compilation？thx!

**Comment by philipturner** [comment]
SIMD async copies are hidden from the Metal Shading Language by Apple, so they cannot be accessed from JIT kernel compilation. That is a major factor motivating the design of MFA: I post pre-compiled binaries, so users don't have to execute the complicated compilation workflow. Please read through the README and build script source code to learn how MFA should be used.
