### ISSUE TITLE
Add flex attention

### ISSUE THREAD

**Issue by JackYoustra** [philipturner/metal-flash-attention#26]
Mentioned at the end of the README

**Comment by JackYoustra** [comment]
(feel free to assign me to this)

**Comment by philipturner** [comment]
The purpose of this reference implementation is to be as simple as possible. It focuses on the core components of the FlashAttention algorithms itself, the dense blocks of computation. Add-on features like batching, multi-head, ALiBi, group query, etc. are trivial once you have the correct foundation.

Regarding block sparsity, I previously tried that in "v1.0" of this repository. It was an unnecessary technical debt and tangential feature, so I removed it. All block sparsity is, is defining chunks of work at a higher level (e.g. 32x32 blocks) and efficiently distributing work subunits across processors. Each work subunit performs "dense" computation, which is the bottleneck that my repo solves. I have done this many times; such an algorithm is used in [OpenMM](https://openmm.org/) to block-sparsify the $O(n^2)$ nonbonded forces. There are so many ways you can do block sparsity, and different contexts require different variations.

It is not my job to create one non-generalizable instance of the many ways you might want to distribute dense work. Just to show (the only/physical optimum) way to execute a dense work unit itself.

**Comment by JackYoustra** [comment]
I see! I was going off of the bottom of the readme, if there are other things that you want people to tackle, it may be helpful to put them there

**Comment by philipturner** [comment]
My goal is to leave this repository in an unmaintained state. I was hired to do this, but not out of personal interest (more to pay the bills). I designed it, so it would be as useful as possible to my client, without requiring me to do additional work after the summer had ended.
