### ISSUE TITLE
Guidelines for modifying H3 with metal-flash-attention

### ISSUE THREAD

**Issue by okpatil4u** [philipturner/metal-flash-attention#3]
Hello Philip,

Great project ! It has been something I have been waiting for some time now.

Can you give me some guideline on how I can replace current flash attention mechanism in [H3](https://github.com/HazyResearch/H3) with metal-flash-attention ?

Thanks in advance !

**Comment by okpatil4u** [comment]
Just to followup,

from [this](https://github.com/HazyResearch/H3/blob/main/src/models/ssm_seq.py) code sample,


```
from flash_attn.modules.mha import MHA
from flash_attn.modules.mlp import Mlp, FusedMLP
from flash_attn.modules.block import Block
from flash_attn.modules.embedding import GPT2Embeddings
from flash_attn.utils.generation import GenerationMixin
```

One would need to replace these imports with metal-flash-attention implementation. Could you please let me know what is the current status for each of them ? And what would be a good starting point for implementing them.

**Comment by philipturner** [comment]
You would have to call into Metal directly using the PyObjC bindings - check out how Tinygrad does this.

**Comment by okpatil4u** [comment]
Hmm, I thought that FlashAttention was one mechanism and alternative to it was FlashConv. Do you think FlashConv will be faster in metal compared to CUDA ?

I will check Tinygrad.

**Comment by philipturner** [comment]
> Do you think FlashConv will be faster in metal compared to CUDA ?

There is no direct way to compare "speed" between Metal and CUDA, as they run on different GPUs with different GFLOPS. Only ways to tell how well a shader utilizes the ALU hardware.

You'll have to look at the algorithm. See whether it has less total operations, and whether it parallelizes efficiently (no workload imbalance).

**Comment by okpatil4u** [comment]
Thanks for the reply. I will look into it.

**Comment by okpatil4u** [comment]
On the same note, yesterday huggingface released [candle](https://github.com/huggingface/candle/tree/main/candle-flash-attn) where they are using cutlass for flash attention. Does metal-flash-attention have all the functionalities to replace cutlass ? I can allocate more resources if that is the case.
